routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::post('/register-orangtua', 'HomeController@RegisterOrangTua')->name('orangtua.register');

Auth::routes();

Route::get('/images/{folder}/{filename}', function ($folder, $filename) {
    $path = public_path('/storage/' . $folder . '/' . $filename);
    if (!File::exists($path)) {
        abort(404);
    }
    $file = File::get($path);
    $type = File::mimeType($path);
    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);
    return $response;
});

Route::group([
    'middleware' => ['auth', 'role:Admin'],
    'prefix' => 'admin',
    'as' => 'admin.'
], function () {
    Route::redirect('', '/admin/home');
    Route::get('/home',  'HomeController@AdminDashboard')->name('home');

    Route::resource('posyandu', 'PosyanduController');
    Route::resource('petugas', 'PetugasController');
    Route::resource('orangtua', 'OrangTuaController');

    Route::get('posyandu-rekap', 'PosyanduController@rekap_penimbangan_desa')->name('posyandu.rekap');
    Route::get('posyandu-rekap-print', 'PosyanduController@rekap_penimbangan_desa_print')->name('posyandu.rekap.print');
});

Route::group([
    'middleware' => ['auth', 'role:Petugas'],
    'prefix' => 'petugas',
    'as' => 'petugas.'
], function () {
    Route::redirect('', '/petugas/home');
    Route::get('/home',  'HomeController@PetugasDashboard')->name('home');

    Route::get('/cari-anak', 'AnakController@index')->name('anak.cari-anak');

    Route::get('/anak', function () {
        return view('petugas.anak.index');
    })->name('anak.index');

    Route::get('/anak/detail', function () {
        return view('petugas.anak.detail');
    })->name('anak.detail');

    Route::post('/confirm-anak/{id}', 'AnakController@ConfirmAnak')->name('confirm.anak');

    Route::resource('jadwal-kegiatan', 'JadwalKegiatanController');

    Route::get('posyandu-report', 'PenimbanganController@PosyanduReport')->name('posyandu.report');
    Route::get('posyandu-print', 'PenimbanganController@PosyanduPrint')->name('posyandu.print');

    Route::group([
        'prefix' => 'anak',
        'as' => 'anak.'
    ], function () {
        // Reports
        Route::get('imunisasi/report', 'ImunisasiController@report')->name('imunisasi.report');
        Route::get('vitamin/report', 'VitaminAController@report')->name('vitamin.report');
        Route::get('penimbangan/report', 'PenimbanganController@report')->name('penimbangan.report');

        // Prints
        Route::get('imunisasi/print', 'ImunisasiController@print')->name('imunisasi.print');
        Route::get('vitamin/print', 'VitaminAController@print')->name('vitamin.print');
        Route::get('penimbangan/print', 'PenimbanganController@print')->name('penimbangan.print');
        Route::group(['middleware' => 'NotInAnakSession'], function () {
            Route::resource('imunisasi', 'ImunisasiController')->except('show');
            Route::resource('vitamin', 'VitaminAController')->except('show');
            Route::resource('penimbangan', 'PenimbanganController')->except('show');
            Route::get('grafik', 'PenimbanganController@grafik')->name('penimbangan.grafik');
        });
    });
});

Route::group([
    'middleware' => ['auth', 'role:Orang_Tua'],
    'prefix' => 'orangtua',
    'as' => 'orangtua.'
], function () {
    Route::redirect('', '/orangtua/home');
    Route::get('/home',  'HomeController@OrangTuaDashboard')->name('home');

    Route::get('/pilih-anak', 'OrangTuaController@PilihAnak')->name('pilih_anak');
    Route::get('/tambah-anak', 'OrangTuaController@TambahAnak')->name('tambah_anak');
    Route::post('/confirm-anak/{id}', 'AnakController@ConfirmAnak')->name('confirm.anak');

    Route::resource('jadwal-kegiatan', 'JadwalKegiatanController')->only('index');

    Route::group([
        'prefix' => 'anak',
        'as' => 'anak.'
    ], function () {
        Route::redirect('', '/orangtua/anak/data');
        Route::resource('data', 'AnakController');
        Route::group(['middleware' => 'NotInAnakSession'], function () {
            Route::resource('imunisasi', 'ImunisasiController')->only('index');
            Route::resource('vitamin', 'VitaminAController')->only('index');
            Route::resource('penimbangan', 'PenimbanganController')->only('index');
            Route::get('grafik', 'PenimbanganController@grafik')->name('penimbangan.grafik');
        });
    });
});

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::get('jenis-imunisasi/{jenis}', function ($jenis) {
        return view('shared.jenis-imunisasi.' . $jenis);
    });
    Route::get('password', 'ProfileController@password')->name('profiles.get.password');
    Route::put('password', 'ProfileController@passwordPost')->name('profiles.post.password');
    Route::get('profile', 'ProfileController@profile')->name('profiles.get.profile');
    Route::put('profile', 'ProfileController@profilePost')->name('profiles.post.profile');
});

app/Http/Controllers/JadwalKegiatanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Jadwal;
use App\Models\Posyandu;
use Illuminate\Http\Request;
use App\Http\Requests\JadwalRequest;
use Illuminate\Support\Facades\DB;

class JadwalKegiatanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = Jadwal::filter($request)->with('posyandu')->orderBy('created_at', 'ASC')->paginate(10);

        $views = [
            'datas' => $data
        ];

        return view('shared.jadwal-kegiatan.index')->with($views);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tempat_kegiatan = Posyandu::orderBy('code', 'ASC')->get();
        $views = [
            'tempat_kegiatan'   => $tempat_kegiatan
        ];

        return view('shared.jadwal-kegiatan.create')->with($views);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(JadwalRequest $request)
    {
        DB::beginTransaction();
        try {
            $wew = Jadwal::create($request->all());

            DB::commit();

            $request->session()->flash('messages', 'Berhasil Menambahkan Data Jadwal Kegiatan');
            $request->session()->flash('type', 'success');

            return redirect()->route('petugas.jadwal-kegiatan.index');
        } catch (\Exception $e) {
            DB::rollback();

            return $e->getMessage();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Jadwal::findOrFail($id);
        $views = [
            'data'              => $data,
        ];

        return view('shared.jadwal-kegiatan.show')->with($views);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Jadwal::findOrFail($id);
        $tempat_kegiatan = Posyandu::orderBy('code', 'ASC')->get();
        $views = [
            'data'              => $data,
            'tempat_kegiatan'   => $tempat_kegiatan
        ];

        return view('shared.jadwal-kegiatan.edit')->with($views);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(JadwalRequest $request, $id)
    {
        DB::beginTransaction();
        try {
            $data = Jadwal::findOrFail($id);
            $data->update($request->all());

            DB::commit();

            $request->session()->flash('messages', 'Berhasil Mengubah Data Jadwal Kegiatan');
            $request->session()->flash('type', 'success');

            return redirect()->route('petugas.jadwal-kegiatan.index');
        } catch (\Exception $e) {
            DB::rollback();

            return $e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        DB::beginTransaction();
        try {
            $data = Jadwal::findOrFail($id);

            $data->delete();

            DB::commit();

            $request->session()->flash('messages', 'Berhasil Menghapus Data Jadwal Kegiatan');
            $request->session()->flash('type', 'success');

            return redirect()->back();
        } catch (\Exception $e) {
            DB::rollback();

            return $e->getMessage();
        }
    }
}

resources/views/shared/jadwal-kegiatan/create.blade.php
@extends('layouts.app')

@section('content')
<form method="POST" action={{ route('petugas.jadwal-kegiatan.store') }}>
  @csrf
  <div class="card">
    <div class="card-header">
        <strong>Jadwal Kegiatan</strong>
        <small> Tambah</small>
    </div>
    <div class="card-body card-block">
      <div class="row">
        <div class="col">
          <div class="form-group">
            <label for="tanggal" class="form-control-label">Tanggal</label>
            <input name="tanggal" type="text" id="tanggal" placeholder="Masukkan tanggal"
              class="form-control @error('tanggal') is-invalid @enderror"
              value={{ old('tanggal') }}>
            @error('tanggal')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
        </div>
        <div class="col">
          <div class="form-group">
            <label for="jam" class="form-control-label">Jam</label>
            <input name="jam" type="text" id="jam" placeholder="Pilih jam"
              class="form-control @error('jam') is-invalid @enderror"
              value={{ old('jam') }}>
            @error('jam')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="posyandu" class="form-control-label">Tempat Kegiatan (posyandu)</label>
        <select name="posyandu_id" id="posyandu" class="form-control @error('posyandu_id') is-invalid @enderror">
          <option disabled selected value="0">Pilih tempat kegiatan</option>
          @foreach ($tempat_kegiatan as $posyandu)
            <option value={{ $posyandu->id }} @if(old('posyandu_id') == $posyandu->id) selected @endif>{{ $posyandu->name }}</option>
          @endforeach
        </select>
        @error('posyandu_id')
          <div class="invalid-feedback">
            {{ $message }}
          </div>
        @enderror
      </div>
      <div class="form-group">
        <label for="nama_kegiatan" class="form-control-label">Nama kegiatan</label>
        <input name="kegiatan" type="text" id="nama_kegiatan" placeholder="Masukkan nama kegiatan"
          class="form-control @error('kegiatan') is-invalid @enderror"
          value={{ old('kegiatan') }}>
        @error('kegiatan')
          <div class="invalid-feedback">
            {{ $message }}
          </div>
        @enderror
      </div>
    </div>
    <div class="card-footer text-right">
      <a href={{ url('/petugas/jadwal-kegiatan') }} type="reset" class="btn btn-danger">
        <i class="fa fa-ban"></i> Cancel
      </a>
      <button type="submit" class="btn btn-primary">
        <i class="fa fa-send"></i> Submit
      </button>
    </div>
  </div>
</form>
@endsection

@push('script-addon')
  <script>
    $('#jam').datetimepicker({
      format: 'HH:mm',
    });
  </script>
@endpush

resources/views/shared/jadwal-kegiatan/edit.blade.php
@extends('layouts.app')

@section('content')
<form method="POST" action={{ route('petugas.jadwal-kegiatan.update', $data->id) }}>
  @csrf
  @method('PUT')
  <div class="card">
    <div class="card-header">
        <strong>Jadwal Kegiatan</strong>
        <small> Edit</small>
    </div>
    <div class="card-body card-block">
      <div class="row">
        <div class="col">
          <div class="form-group">
            <label for="tanggal" class="form-control-label">Tanggal</label>
            <input name="tanggal" type="text" id="tanggalss" placeholder="Masukkan tanggal"
              class="form-control @error('tanggal') is-invalid @enderror"
              value="{{ $data->tanggal }}">
            @error('tanggal')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
        </div>
        <div class="col">
          <div class="form-group">
            <label for="jam" class="form-control-label">Jam</label>
            <input name="jam" type="text" id="jam" placeholder="Pilih jam"
              class="form-control @error('jam') is-invalid @enderror"
              value="{{ $data->jam }}">
            @error('jam')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="posyandu" class="form-control-label">Tempat Kegiatan (posyandu)</label>
        <select name="posyandu_id" id="posyandu" class="form-control @error('posyandu_id') is-invalid @enderror">
          <option disabled selected value="0">Pilih tempat kegiatan</option>
          @foreach ($tempat_kegiatan as $posyandu)
            <option value="{{ $posyandu->id }}" @if($data->posyandu_id == $posyandu->id) selected @endif>{{ $posyandu->name }}</option>
          @endforeach
        </select>
        @error('posyandu_id')
          <div class="invalid-feedback">
            {{ $message }}
          </div>
        @enderror
      </div>
      <div class="form-group">
        <label for="nama_kegiatan" class="form-control-label">Nama kegiatan</label>
        <input name="kegiatan" type="text" id="nama_kegiatan" placeholder="Masukkan nama kegiatan"
          class="form-control @error('kegiatan') is-invalid @enderror"
          value="{{ $data->kegiatan }}">
        @error('kegiatan')
          <div class="invalid-feedback">
            {{ $message }}
          </div>
        @enderror
      </div>
    </div>
    <div class="card-footer text-right">
      <a href={{ url('/petugas/jadwal-kegiatan') }} type="reset" class="btn btn-danger">
        <i class="fa fa-ban"></i> Cancel
      </a>
      <button type="submit" class="btn btn-primary">
        <i class="fa fa-send"></i> Submit
      </button>
    </div>
  </div>
</form>
@endsection

@push('script-addon')
  <script>
    $('#jam').datetimepicker({
      format: 'HH:mm',
    });
  </script>
@endpush

resources/views/shared/jadwal-kegiatan/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
  <div class="row m-b-25">
    <div class="col-md-12">
      <div class="overview-wrap">
        <h2 class="title-1">Jadwal Kegiatan</h2>
        @role('Petugas')
          <a
            class="au-btn au-btn-icon au-btn--blue"
            href={{ url('/petugas/jadwal-kegiatan/create') }}
          >
            <i class="zmdi zmdi-plus"></i>
            Tambah jadwal kegiatan
          </a>
        @endrole
      </div>
    </div>
  </div>
  @if ($msg = Session::get('messages'))
    <div class="row">
      <div class="col col-12">
        <div class="alert alert-block alert-{{ Session::get('type') }}">
          <p>{{ $msg }}</p>
        </div>      
      </div>
    </div>
  @endif
  <div class="row">
    <div class="col col-12">
      <div class="table-responsive">
        <table class="table table-borderless table-data3">
          <thead>
            <tr>
              <th>tanggal</th>
              <th>jam</th>
              <th>tempat kegiatan</th>
              <th>kecamatan</th>
              <th>kelurahan/desa</th>
              <th>alamat</th>
              <th>kegiatan</th>
              @role('Petugas')
                <th>option</th>
              @endrole
            </tr>
          </thead>
          <tbody>
            @forelse ($datas as $dt)
              <tr>
                <td>{{ $dt->tanggal }}</td>
                <td>{{ $dt->jam_formatted }}</td>
                <td>{{ $dt->posyandu->name }}</td>
                <td>{{ $dt->posyandu->kecamatan }}</td>
                <td>{{ $dt->posyandu->desa }}</td>
                <td>{{ $dt->posyandu->alamat }}</td>
                <td>{{ $dt->kegiatan }}</td>
                @role('Petugas')
                  <td>
                    <a class="btn btn-sm btn-info d-inline-block" href={{ url('/petugas/jadwal-kegiatan/'. $dt->id .'/edit') }}>Edit</a>
                    <form class="d-inline-block" method="post" action={{ url('/petugas/jadwal-kegiatan/' . $dt->id) }} onSubmit="return confirm('Ingin menghapus?')">
                      @csrf
                      @method('DELETE')
                      <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                    </form>
                  </td>
                @endrole
              </tr>
            @empty
              <tr>
                <td colspan="100%" class="text-center p-5"><h5>Tidak ada data.</h5></td>
              </tr>
            @endforelse
          </tbody>
        </table>
        <div class="d-flex justify-content-end m-t-25">
          {{ $datas->appends(request()->all())->links() }}
        </div>
      </div>
    </div>
  </div>
</div>
@endsection