routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::post('/register-orangtua', 'HomeController@RegisterOrangTua')->name('orangtua.register');

Auth::routes();

Route::get('/images/{folder}/{filename}', function ($folder, $filename) {
    $path = public_path('/storage/' . $folder . '/' . $filename);
    if (!File::exists($path)) {
        abort(404);
    }
    $file = File::get($path);
    $type = File::mimeType($path);
    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);
    return $response;
});

Route::group([
    'middleware' => ['auth', 'role:Admin'],
    'prefix' => 'admin',
    'as' => 'admin.'
], function () {
    Route::redirect('', '/admin/home');
    Route::get('/home',  'HomeController@AdminDashboard')->name('home');

    Route::resource('posyandu', 'PosyanduController');
    Route::resource('petugas', 'PetugasController');
    Route::resource('orangtua', 'OrangTuaController');

    Route::get('posyandu-rekap', 'PosyanduController@rekap_penimbangan_desa')->name('posyandu.rekap');
    Route::get('posyandu-rekap-print', 'PosyanduController@rekap_penimbangan_desa_print')->name('posyandu.rekap.print');
});

Route::group([
    'middleware' => ['auth', 'role:Petugas'],
    'prefix' => 'petugas',
    'as' => 'petugas.'
], function () {
    Route::redirect('', '/petugas/home');
    Route::get('/home',  'HomeController@PetugasDashboard')->name('home');

    Route::get('/cari-anak', 'AnakController@index')->name('anak.cari-anak');

    Route::get('/anak', function () {
        return view('petugas.anak.index');
    })->name('anak.index');

    Route::get('/anak/detail', function () {
        return view('petugas.anak.detail');
    })->name('anak.detail');

    Route::post('/confirm-anak/{id}', 'AnakController@ConfirmAnak')->name('confirm.anak');

    Route::resource('jadwal-kegiatan', 'JadwalKegiatanController');

    Route::get('posyandu-report', 'PenimbanganController@PosyanduReport')->name('posyandu.report');
    Route::get('posyandu-print', 'PenimbanganController@PosyanduPrint')->name('posyandu.print');

    Route::group([
        'prefix' => 'anak',
        'as' => 'anak.'
    ], function () {
        // Reports
        Route::get('imunisasi/report', 'ImunisasiController@report')->name('imunisasi.report');
        Route::get('vitamin/report', 'VitaminAController@report')->name('vitamin.report');
        Route::get('penimbangan/report', 'PenimbanganController@report')->name('penimbangan.report');

        // Prints
        Route::get('imunisasi/print', 'ImunisasiController@print')->name('imunisasi.print');
        Route::get('vitamin/print', 'VitaminAController@print')->name('vitamin.print');
        Route::get('penimbangan/print', 'PenimbanganController@print')->name('penimbangan.print');
        Route::group(['middleware' => 'NotInAnakSession'], function () {
            Route::resource('imunisasi', 'ImunisasiController')->except('show');
            Route::resource('vitamin', 'VitaminAController')->except('show');
            Route::resource('penimbangan', 'PenimbanganController')->except('show');
            Route::get('grafik', 'PenimbanganController@grafik')->name('penimbangan.grafik');
        });
    });
});

Route::group([
    'middleware' => ['auth', 'role:Orang_Tua'],
    'prefix' => 'orangtua',
    'as' => 'orangtua.'
], function () {
    Route::redirect('', '/orangtua/home');
    Route::get('/home',  'HomeController@OrangTuaDashboard')->name('home');

    Route::get('/pilih-anak', 'OrangTuaController@PilihAnak')->name('pilih_anak');
    Route::get('/tambah-anak', 'OrangTuaController@TambahAnak')->name('tambah_anak');
    Route::post('/confirm-anak/{id}', 'AnakController@ConfirmAnak')->name('confirm.anak');

    Route::resource('jadwal-kegiatan', 'JadwalKegiatanController')->only('index');

    Route::group([
        'prefix' => 'anak',
        'as' => 'anak.'
    ], function () {
        Route::redirect('', '/orangtua/anak/data');
        Route::resource('data', 'AnakController');
        Route::group(['middleware' => 'NotInAnakSession'], function () {
            Route::resource('imunisasi', 'ImunisasiController')->only('index');
            Route::resource('vitamin', 'VitaminAController')->only('index');
            Route::resource('penimbangan', 'PenimbanganController')->only('index');
            Route::get('grafik', 'PenimbanganController@grafik')->name('penimbangan.grafik');
        });
    });
});

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::get('jenis-imunisasi/{jenis}', function ($jenis) {
        return view('shared.jenis-imunisasi.' . $jenis);
    });
    Route::get('password', 'ProfileController@password')->name('profiles.get.password');
    Route::put('password', 'ProfileController@passwordPost')->name('profiles.post.password');
    Route::get('profile', 'ProfileController@profile')->name('profiles.get.profile');
    Route::put('profile', 'ProfileController@profilePost')->name('profiles.post.profile');
});

app/Models/Posyandu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Posyandu extends Model
{
    protected $table = 'posyandu';

    protected $fillable = [
        'code',
        'name',
        'jumlah_kader',
        'alamat',
        'rt',
        'kecamatan',
        'ketua',
        'desa',
    ];

    public $timestamps = true;

    protected $appends = ['status_used', 'jumlah_anak_l',  'jumlah_anak_p'];

    public function vitamin_a()
    {
        return $this->hasMany(VitaminA::class, 'posyandu_id');
    }

    public function imunisasi()
    {
        return $this->hasMany(Imunisasi::class, 'posyandu_id');
    }

    public function petugas()
    {
        return $this->hasMany(Petugas::class, 'posyandu_id');
    }

    public function penimbangan()
    {
        return $this->hasMany(Penimbangan::class, 'posyandu_id');
    }

    public function scopeFilter($query, $request)
    {
        if ($request->has('q')) {
            $query->where('code', 'like', '%' . $request->get('q') . '%')
                ->orWhere('name', 'like', '%' . $request->get('q') . '%')
                ->orWhere('ketua', 'like', '%' . $request->get('q') . '%');
        }

        return $query;
    }

    public function getStatusUsedattribute()
    {
        $status = false;

        $vitamin_a = $this->vitamin_a->count();
        $imunisasi = $this->imunisasi->count();
        $penimbangan = $this->penimbangan->count();
        $petugas = $this->petugas->count();

        if ($vitamin_a > 0) {
            $status = true;
        } elseif ($imunisasi > 0) {
            $status = true;
        } elseif ($penimbangan > 0) {
            $status = true;
        } elseif ($petugas > 0) {
            $status = true;
        }

        return $status;
    }

    public function getJumlahAnakAttribute()
    {
        $penimbangan = $this->penimbangan->groupBy('anak_id')->count();

        return $penimbangan;
    }

    public function getJumlahAnakPAttribute()
    {
        $penimbangan = $this->penimbangan()->whereHas('anak', function ($q) {
            $q->where('jenis_kelamin', 'PR');
        })->groupBy('anak_id')->get()->count();

        return $penimbangan;
    }

    public function getJumlahAnakLAttribute()
    {
        $penimbangan = $this->penimbangan()->whereHas('anak', function ($q) {
            $q->where('jenis_kelamin', 'LK');
        })->groupBy('anak_id')->get()->count();

        return $penimbangan;
    }
}

resources/views/petugas/anak/reports/print/imunisasi.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ asset('css/papper.css') }}">
    <link href="{{ asset('template/vendor/bootstrap-4.1/bootstrap.min.css') }}" rel="stylesheet" media="all">
    <link rel="stylesheet" href="{{ asset('css/custom.css') }}" type="text/css">
    <style>
        .label-print{
            font-size: 100%;
            font-weight: lighter;
        }

        hr {
            margin-top: 20px;
            margin-bottom: 20px;
            border: 1px;
            border-top: 4px solid black;
        }
        
        .table-custom th {
            border: 1px solid black;
            font-weight: bold;
            background:#f3d89c;
            text-align: center;
        }


        .table-custom td, .table-custom th {
            border: 1px solid black;
            text-align: center;
        }
        
        .table-custom {
            border: 1px solid;
            margin-top: 8px;
            width: 100%;
        }
        

    </style>
    <title></title>
</head>
<body onload="window.print();">
    <section class="A4 sheet padding-0mm1">
        <article>
          Monggo
        </article>
    </section>
</body>
</html>

resources/views/petugas/anak/reports/print/penimbangan.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="{{ asset('css/papper.css') }}">
	<link href="{{ asset('template/css/theme.css') }}" rel="stylesheet" media="all">

	<title>Laporan Penimbangan</title>

	<style>
		html, body {
			font-size: 14px;
		}

		.header {
			border-bottom: 3px solid black;
			display: flex;
			flex-direction: row;
			padding-bottom: 20px;
			margin-bottom: 20px;
		}

		.logo {
			width: 100px;
			height: 100px;
		}

		.header-info {
			display: flex;
			flex: 1;
			flex-direction: column;
			justify-content: center;
			align-items: center;
      margin: 0 20px;
		}

		.heading {
			font-size: 1.6em;
			margin: 2px 0;
      text-align: center;
		}

		.content-heading {
			font-size: 1.6em;
		}

		.content-info {
			align-self: flex-start;
		}

		.content-info p {
			margin: 5px 0;
		}

		.table {
			width: 100%;
			border-collapse: collapse;
			margin-top: 20px;
		}

		.table th, .table td{
			border: 2px solid black;
			padding: 5px;
		}

		.text-center {
			text-align: center;
		}

    .font-weight-bold {
      font-weight: bold;
    }
    
    .footer {
      width: 100%;
      margin-top: 40px;
      display: flex;
      justify-content: flex-end;
      position: relative;
    }

    .ttd-text {
      margin-bottom: 70px;
    }

    @media print {
      .table th, .table td, .footer {
        page-break-inside: avoid;
      }
    }
		
	</style>
</head>
<body onload="window.print();" class="A4.landscape">
	<section class="sheet padding-10mm">
		<article>
			<div class="header">
				<img class="logo" src="{{ asset('template/images/icon/kukar-logo.png') }}" alt="Logo Kukar">
				<div class="header-info"">
					<h1 class="heading">PEMERINTAH KABUPATEN KUTAI KARTANEGARA</h1>
					<h1 class="heading">UPT DINAS KESEHATAN</h1>
					<h1 class="heading">PUSKESMAS SUNGAI MARIAM</h1>
					<h1 class="heading">KECAMATAN ANGGANA</h1>
					<p class="address">Jl. Mulawarman RT. 1 No. 03. Telp. 0541-682412 Kode Pos 75381</p>
				</div>
			</div>
			
			<div class="content">
				<h2 class="content-heading text-center">Laporan Penimbangan</h2>
				
				<div class="content-info">
					<p>Posyandu: {{ Auth::user()->petugas->posyandu->name }}</p>
					<p>Tanggal: {{ $tanggal }}</p>
				</div>

				<table class="table">
					<thead>
						<tr>
								<th>No. Identitas Anak</th>
								<th>Nama Anak</th>
								<th>Tanggal Lahir</th>
								<th>Orangtua</th>
								<th>Berat Badan (kg)</th>
								<th>Tinggi Badan (cm)</th>
								<th>Keterangan</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($datas as $dt)
							<tr>
								<td class="text-center">{{ $dt->anak->generateId }}</td>
								<td>{{ $dt->anak->name }}</td>
								<td class="text-center">{{ $dt->anak->tgl_lahir_formatted }}</td>
								<td class="text-center">{{ $dt->anak->bapak ?? '-' }} / {{ $dt->anak->ibu ?? '-' }}</td>
								<td class="text-center">{{ $dt->berat_badan }} kg</td>
								<td class="text-center">{{ $dt->tinggi_badan }} cm</td>
								<td>{{ $dt->keterangan_formatted }}</td>
							</tr>
						@endforeach
					</tbody>
				</table>

				<div class="footer">
          <div class="ttd">
            <p class="ttd-text">
              Sungai Mariam,<br>
              Ketua Kader Posyandu
            </p>
            <p>(....................................)</p>
          </div>
        </div>
			</div>
		</article>
	</section>
</body>
</html>

resources/views/petugas/anak/reports/print/posyandu-rekap.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="{{ asset('css/papper.css') }}">
	<link href="{{ asset('template/css/theme.css') }}" rel="stylesheet" media="all">

	<title>Laporan Posyandu</title>

	<style>
		html, body {
			font-size: 14px;
		}

		.header {
			border-bottom: 3px solid black;
			display: flex;
			flex-direction: row;
			padding-bottom: 20px;
			margin-bottom: 20px;
		}

		.logo {
			width: 100px;
			height: 100px;
		}

		.header-info {
			display: flex;
			flex: 1;
			flex-direction: column;
			justify-content: center;
			align-items: center;
      margin: 0 20px;
		}

		.heading {
			font-size: 1.6em;
			margin: 2px 0;
      text-align: center;
		}

		.content-heading {
			font-size: 1.6em;
		}

		.content-info {
			align-self: flex-start;
		}

		.content-info p {
			margin: 5px 0;
		}

		.table {
			width: 100%;
			border-collapse: collapse;
			margin-top: 20px;
		}

		.table th, .table td{
			border: 2px solid black;
			padding: 5px;
		}

		.text-center {
			text-align: center;
		}

    .font-weight-bold {
      font-weight: bold;
    }
    
    .footer {
      width: 100%;
      margin-top: 40px;
      display: flex;
      justify-content: flex-end;
      position: relative;
    }

    .ttd-text {
      margin-bottom: 70px;
    }

    @media print {
      .table th, .table td, .footer {
        page-break-inside: avoid;
      }
    }
		
	</style>
</head>
<body onload="window.print();" class="A4.potrait">
	<section class="sheet padding-10mm">
		<article>
      <div class="header">
				<img class="logo" src="{{ asset('template/images/icon/kukar-logo.png') }}" alt="Logo Kukar">
				<div class="header-info">
					<h1 class="heading">LAPORAN REKAP PENIMBANGAN DESA</h1>
          <h1 class="heading">WILAYAH KERJA PUSKESMAS SUNGAI MARIAM</h1>
				</div>
				{{-- <img class="logo" src="{{ asset('template/images/icon/puskesmas-logo.png') }}" alt="Logo Kukar"> --}}
			</div>
			
			<div class="content">		
				<div class="content-info">
          <p><span class="font-weight-bold">Kecamata:</span> Anggana</p>
          <p><span class="font-weight-bold">Kelurahan/Desa:</span> {{ $kelurahan }}</p>
          <p><span class="font-weight-bold">Tanggal:</span> {{ $tanggal }}</p>
				</div>
        
				<table class="table">
					<thead>
						<tr>
              <th>NO</th>
              <th>NAMA POSYANDU</th>
              <th>ALAMAT</th>
              <th>RT</th>
              <th>L</th>
              <th>P</th>
              <th>TOTAL</th>
            </tr>
					</thead>
					<tbody>
            @foreach ($datas as $dt)
              <tr>
                <td class="text-center">
                  {{ $loop->iteration }}
                </td>
                <td>
                  {{ $dt->name }}
                </td>
                <td>
                  {{ $dt->alamat }}
                </td>
                <td class="text-center">
                  {{ $dt->rt }}
                </td>
                <td class="text-center">
                  {{ $dt->jumlah_anak_l }}
                </td>
                <td class="text-center">
                  {{ $dt->jumlah_anak_p }}
                </td>
                <td class="text-center">
                  {{ $dt->jumlah_anak }}
                </td>
              </tr>
            @endforeach
            <tr>
              <td colspan="6" class="text-center">JUMLAH</td>
              <td class="text-center">{{ $jumlah }}</td>
            </tr>
					</tbody>
        </table>
        
        <div class="footer">
          <div class="ttd">
            <p class="ttd-text">
              Sungai Mariam,<br>
              Ketua Kader Posyandu
            </p>
            <p>(....................................)</p>
          </div>
        </div>
			</div>
		</article>
  </section>
</body>
</html>

resources/views/petugas/anak/reports/print/vitamin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="{{ asset('css/papper.css') }}">
	<link href="{{ asset('template/css/theme.css') }}" rel="stylesheet" media="all">

	<title>Laporan Vitamin A</title>

	<style>
		html, body {
			font-size: 14px;
		}

		.header {
			border-bottom: 3px solid black;
			display: flex;
			flex-direction: row;
			padding-bottom: 20px;
			margin-bottom: 20px;
		}

		.logo {
			width: 100px;
			height: 100px;
		}

		.header-info {
			display: flex;
			flex: 1;
			flex-direction: column;
			justify-content: center;
			align-items: center;
      margin: 0 20px;
		}

		.heading {
			font-size: 1.6em;
			margin: 2px 0;
      text-align: center;
		}

		.content-heading {
			font-size: 1.6em;
		}

		.content-info {
			align-self: flex-start;
		}

		.content-info p {
			margin: 5px 0;
		}

		.table {
			width: 100%;
			border-collapse: collapse;
			margin-top: 20px;
		}

		.table th, .table td{
			border: 2px solid black;
			padding: 5px;
		}

		.text-center {
			text-align: center;
		}

    .font-weight-bold {
      font-weight: bold;
    }
    
    .footer {
      width: 100%;
      margin-top: 40px;
      display: flex;
      justify-content: flex-end;
      position: relative;
    }

    .ttd-text {
      margin-bottom: 70px;
    }

    @media print {
      .table th, .table td, .footer {
        page-break-inside: avoid;
      }
    }
		
	</style>
</head>
<body onload="window.print();" class="A4.landscape">
	<section class="sheet padding-10mm">
		<article>
			<div class="header">
				<img class="logo" src="{{ asset('template/images/icon/kukar-logo.png') }}" alt="Logo Kukar">
				<div class="header-info"">
					<h1 class="heading">PEMBERIAN KAPSUL VITAMIN A</h1>
					<h1 class="heading">UMUR {{ request()->get('jenis') === 'biru' ? '6-11 BULAN' : '12-59 BULAN' }}</h1>
				</div>
				{{-- <img class="logo" src="{{ asset('template/images/icon/puskesmas-logo.png') }}" alt="Logo Kukar"> --}}
			</div>
			
			<div class="content">			
				<div class="content-info">
					<p>Posyandu: {{ Auth::user()->petugas->posyandu->name }}</p>
					<p>Jenis: Kapsul {{ ucfirst(request()->get('jenis')) }}</p>
					<p>Tanggal: {{ $tanggal }}</p>
				</div>

				<table class="table">
					<thead>
						<tr>
							<th rowspan="2">No. Identitas Anak</th>
							<th rowspan="2">Nama Anak</th>
							<th colspan="2">Orangtua</th>
							<th colspan="2">Tanggal Lahir / Umur</th>
							<th rowspan="2">Jenis Kelamin</th>
							<th rowspan="2">Alamat</th>
						</tr>
						<tr>
							<th>Bapak</th>
							<th>Ibu</th>
							<th>Tanggal Lahir</th>
							<th>Umur</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($datas as $dt)
							<tr>
								<td class="text-center">{{ $dt->anak->generateId }}</td>
								<td>{{ $dt->anak->name }}</td>
								<td>{{ $dt->anak->bapak ?? '-' }}</td>
								<td>{{ $dt->anak->ibu ?? '-' }}</td>
								<td class="text-center">{{ $dt->anak->tgl_lahir_formatted }}</td>
								<td class="text-center">{{ $dt->anak->umur_bulan_formatted }}</td>
								<td>{{ $dt->anak->jenis_kelamin_formatted }}</td>
								<td>{{ $dt->anak->alamat }}</td>
							</tr>
						@endforeach
					</tbody>
				</table>

				<div class="footer">
          <div class="ttd">
            <p class="ttd-text">
              Sungai Mariam,<br>
              Ketua Kader Posyandu
            </p>
            <p>(....................................)</p>
          </div>
        </div>
			</div>
		</article>
	</section>
</body>
</html>