routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::post('/register-orangtua', 'HomeController@RegisterOrangTua')->name('orangtua.register');

Auth::routes();

Route::get('/images/{folder}/{filename}', function ($folder, $filename) {
    $path = public_path('/storage/' . $folder . '/' . $filename);
    if (!File::exists($path)) {
        abort(404);
    }
    $file = File::get($path);
    $type = File::mimeType($path);
    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);
    return $response;
});

Route::group([
    'middleware' => ['auth', 'role:Admin'],
    'prefix' => 'admin',
    'as' => 'admin.'
], function () {
    Route::redirect('', '/admin/home');
    Route::get('/home',  'HomeController@AdminDashboard')->name('home');

    Route::resource('posyandu', 'PosyanduController');
    Route::resource('petugas', 'PetugasController');
    Route::resource('orangtua', 'OrangTuaController');

    Route::get('posyandu-rekap', 'PosyanduController@rekap_penimbangan_desa')->name('posyandu.rekap');
    Route::get('posyandu-rekap-print', 'PosyanduController@rekap_penimbangan_desa_print')->name('posyandu.rekap.print');
});

Route::group([
    'middleware' => ['auth', 'role:Petugas'],
    'prefix' => 'petugas',
    'as' => 'petugas.'
], function () {
    Route::redirect('', '/petugas/home');
    Route::get('/home',  'HomeController@PetugasDashboard')->name('home');

    Route::get('/cari-anak', 'AnakController@index')->name('anak.cari-anak');

    Route::get('/anak', function () {
        return view('petugas.anak.index');
    })->name('anak.index');

    Route::get('/anak/detail', function () {
        return view('petugas.anak.detail');
    })->name('anak.detail');

    Route::post('/confirm-anak/{id}', 'AnakController@ConfirmAnak')->name('confirm.anak');

    Route::resource('jadwal-kegiatan', 'JadwalKegiatanController');

    Route::get('posyandu-report', 'PenimbanganController@PosyanduReport')->name('posyandu.report');
    Route::get('posyandu-print', 'PenimbanganController@PosyanduPrint')->name('posyandu.print');

    Route::group([
        'prefix' => 'anak',
        'as' => 'anak.'
    ], function () {
        // Reports
        Route::get('imunisasi/report', 'ImunisasiController@report')->name('imunisasi.report');
        Route::get('vitamin/report', 'VitaminAController@report')->name('vitamin.report');
        Route::get('penimbangan/report', 'PenimbanganController@report')->name('penimbangan.report');

        // Prints
        Route::get('imunisasi/print', 'ImunisasiController@print')->name('imunisasi.print');
        Route::get('vitamin/print', 'VitaminAController@print')->name('vitamin.print');
        Route::get('penimbangan/print', 'PenimbanganController@print')->name('penimbangan.print');
        Route::group(['middleware' => 'NotInAnakSession'], function () {
            Route::resource('imunisasi', 'ImunisasiController')->except('show');
            Route::resource('vitamin', 'VitaminAController')->except('show');
            Route::resource('penimbangan', 'PenimbanganController')->except('show');
            Route::get('grafik', 'PenimbanganController@grafik')->name('penimbangan.grafik');
        });
    });
});

Route::group([
    'middleware' => ['auth', 'role:Orang_Tua'],
    'prefix' => 'orangtua',
    'as' => 'orangtua.'
], function () {
    Route::redirect('', '/orangtua/home');
    Route::get('/home',  'HomeController@OrangTuaDashboard')->name('home');

    Route::get('/pilih-anak', 'OrangTuaController@PilihAnak')->name('pilih_anak');
    Route::get('/tambah-anak', 'OrangTuaController@TambahAnak')->name('tambah_anak');
    Route::post('/confirm-anak/{id}', 'AnakController@ConfirmAnak')->name('confirm.anak');

    Route::resource('jadwal-kegiatan', 'JadwalKegiatanController')->only('index');

    Route::group([
        'prefix' => 'anak',
        'as' => 'anak.'
    ], function () {
        Route::redirect('', '/orangtua/anak/data');
        Route::resource('data', 'AnakController');
        Route::group(['middleware' => 'NotInAnakSession'], function () {
            Route::resource('imunisasi', 'ImunisasiController')->only('index');
            Route::resource('vitamin', 'VitaminAController')->only('index');
            Route::resource('penimbangan', 'PenimbanganController')->only('index');
            Route::get('grafik', 'PenimbanganController@grafik')->name('penimbangan.grafik');
        });
    });
});

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::get('jenis-imunisasi/{jenis}', function ($jenis) {
        return view('shared.jenis-imunisasi.' . $jenis);
    });
    Route::get('password', 'ProfileController@password')->name('profiles.get.password');
    Route::put('password', 'ProfileController@passwordPost')->name('profiles.post.password');
    Route::get('profile', 'ProfileController@profile')->name('profiles.get.profile');
    Route::put('profile', 'ProfileController@profilePost')->name('profiles.post.profile');
});

app/Models/Anak.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Anak extends Model
{
    protected $table = 'anak';

    protected $fillable = [
        'nik',
        'name',
        'tgl_lahir',
        'jenis_kelamin',
        'rt',
        'alamat',
        'kecamatan',
        'kelurahan',
        'ortu_id',
        'generateId',
        'foto',
        'bapak',
        'ibu',
        'is_in_anggana'
    ];

    protected $dates = [
        'tgl_lahir',
    ];

    public $timestamps = true;

    protected $appends = [
        'status_used',
        'umur',
        'tgl_lahir_formatted',
        'jenis_kelamin_formatted',
        'umur_bulan',
        'umur_bulan_formatted',
        'is_in_anggana_formatted',
        'baru',
        'naik',
        'turun',
        'tidak_timbang'
    ];

    public function orang_tua()
    {
        return $this->belongsTo(OrangTua::class, 'ortu_id');
    }

    public function vitamin_a()
    {
        return $this->hasMany(VitaminA::class, 'anak_id');
    }

    public function imunisasi()
    {
        return $this->hasMany(Imunisasi::class, 'anak_id');
    }

    public function penimbangan()
    {
        return $this->hasMany(Penimbangan::class, 'anak_id');
    }

    public function penimbangan_turun()
    {
        return $this->hasMany(Penimbangan::class, 'anak_id')->where('keterangan', '2');
    }

    public function scopeFilter($query, $request)
    {
        if ($request->has('q')) {
            $query->where('name', 'like', '%' . $request->get('q') . '%')
                ->orWhere('generateId', 'like', '%' . $request->get('q') . '%')
                ->OrWhereHas('orang_tua', function ($q) use ($request) {
                    $q->whereHas('orang_tua', function ($q) use ($request) {
                        $q->whereHas('user', function ($q) use ($request) {
                            $q->where('name', 'like', '%' . $request->get('q') . '%');
                        });
                    });
                });
        }

        return $query;
    }

    public function scopeLaki($query)
    {
        $query->where('jenis_kelamin', 'LK');
    }

    public function scopePerempuan($query)
    {
        $query->where('jenis_kelamin', 'PR');
    }

    public function getBaruattribute()
    {
        return $this->penimbangan()->where('keterangan', '0')->count();
    }

    public function getNaikattribute()
    {
        return $this->penimbangan()->where('keterangan', '1')->count();
    }

    public function getTurunattribute()
    {
        return $this->penimbangan()->where('keterangan', '2')->count();
    }

    public function getTidakTimbangattribute()
    {
        return $this->penimbangan()->where('keterangan', '3')->count();
    }

    public function getStatusUsedattribute()
    {
        $status = false;

        $vitamin_a = $this->vitamin_a->count();
        $imunisasi = $this->imunisasi->count();
        $penimbangan = $this->penimbangan->count();

        if ($vitamin_a > 0) {
            $status = true;
        } elseif ($imunisasi > 0) {
            $status = true;
        } elseif ($penimbangan > 0) {
            $status = true;
        }

        return $status;
    }

    public function getTglLahirFormattedattribute()
    {
        return $this->tgl_lahir->format('d F Y');
    }

    public function getUmurattribute()
    {
        $umur = $this->tgl_lahir->diff(Carbon::now())->format('%y Tahun %m Bulan dan %d Hari');

        return $umur;
    }

    public function getUmurBulanattribute()
    {
        $umur = $this->tgl_lahir->diffInMonths(Carbon::now());

        return $umur;
    }

    public function getUmurBulanFormattedattribute()
    {
        $umur = $this->tgl_lahir->diffInMonths(Carbon::now());

        return $umur . ' Bulan';
    }

    public function getJenisKelaminFormattedattribute()
    {
        if ($this->jenis_kelamin === 'LK') return 'Laki-laki';
        else return 'Perempuan';
    }

    public function getIsInAngganaFormattedattribute()
    {
        if ($this->is_in_anggana) {
            $stat = 'Warga Anggana';
        } else {
            $stat = 'Warga Luar Anggana';
        }

        return $stat;
    }
}

app/Http/Controllers/AnakController.php
<?php

namespace App\Http\Controllers;

use DB;
use App\Models\Anak;
use App\Models\Petugas;
use App\Models\OrangTua;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Requests\AnakRequest;

class AnakController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $role = auth()->user()->getRoleNames()->first();
        switch ($role) {
            case 'Petugas':
                $anak = Anak::filter($request)->with('orang_tua')->orderBy('name', 'ASC')->paginate(10);
                $prefix = 'petugas.cari-anak.index';
                break;

            default:
                $anak = Anak::filter($request)->with('orang_tua')->whereHas('orang_tua', function ($q) {
                    $q->where('ortu_id', auth()->user()->orang_tua->id);
                })->orderBy('name', 'ASC')->paginate(10);
                $prefix = 'orangtua.anak.index';
                break;
        }

        $view = [
            'datas'  => $anak
        ];

        return view($prefix)->with($view);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $ibu = OrangTua::whereHas('user', function ($q) {
            $q->where('jenis_kelamin', 'PR');
        })->with('user')->get()->pluck('user.name', 'id');

        $bapak = OrangTua::whereHas('user', function ($q) {
            $q->where('jenis_kelamin', 'LK');
        })->with('user')->get()->pluck('user.name', 'id');

        $views = [
            'bapak' => $bapak,
            'ibu'   => $ibu,
        ];

        return view('orangtua.anak.create')->with($views);
    }

    /**
     * Store a newly created resource in storage.
     *
     * Request: name, tgl_lahir, jenis_kelamin, alamat, bapak_id, ibu_id, foto
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AnakRequest $request)
    {
        DB::beginTransaction();
        try {

            $file = $request->foto;
            $slug = Str::slug($file->getClientOriginalName(), '_');
            $photo = time() . $slug . '.' . $file->getClientOriginalExtension();

            $generateId = explode('/', $request->tgl_lahir);
            $generateId = implode('', $generateId);
            $generateId = $generateId . rand(1111, 9999);
            $in_anggana = false;

            if (Str::substr($request->no_ktp ?? $request->nik, 0, 6) == 640204) {
                $in_anggana = true;
            }

            $request->merge([
                'generateId'    => $generateId,
                'ortu_id'       => auth()->user()->orang_tua->id,
                'is_in_anggana' => $in_anggana
            ]);

            $anak = Anak::create($request->all());
            $anak->update(['foto'  => $photo]);

            $this->SavePhotoNR($file, $photo, public_path('storage/anak/'));

            DB::commit();

            $request->session()->flash('messages', 'Berhasil Menambahkan Data Anak');
            $request->session()->flash('type', 'success');

            if ($request->session()->get('anak')) {
                $redirect = 'orangtua.anak.data.index';
            } else {
                $redirect = 'orangtua.pilih_anak';
            }

            return redirect()->route($redirect);
        } catch (\Exception $e) {
            DB::rollback();

            return $e->getMessage();
        }
    }

    private function SavePhotoNR($image, $photo, $path)
    {
        $file = $image;
        $file->move($path, $photo);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Anak::with('orang_tua')->findOrFail($id);

        $views = [
            'data' => $data
        ];

        return view('orangtua.anak.show')->with($views);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $data = Anak::with('orang_tua')->findOrFail($id);

        $views = [
            'data' => $data,
        ];

        return view('orangtua.anak.edit')->with($views);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AnakRequest $request, $id)
    {
        DB::beginTransaction();
        try {
            $anak = Anak::findOrFail($id);
            $in_anggana = false;

            if (Str::substr($request->no_ktp ?? $request->nik, 0, 6) == 640204) {
                $in_anggana = true;
            }

            $request->merge([
                'is_in_anggana' => $in_anggana
            ]);

            $anak->update($request->all());

            if (isset($request->foto)) {
                if (!empty($anak->foto)) {
                    \File::delete(public_path('storage/anak/' . $anak->foto));
                }

                $file = $request->foto;
                $slug = Str::slug($file->getClientOriginalName(), '_');
                $photo = time() . $slug . '.' . $file->getClientOriginalExtension();
                $anak->update(['foto' => $photo]);

                $this->SavePhotoNR($file, $photo, public_path('storage/anak/'));
            }

            DB::commit();

            $request->session()->flash('messages', 'Berhasil Mengubah Data Anak');
            $request->session()->flash('type', 'success');

            return redirect()->route('orangtua.anak.data.index');
        } catch (\Exception $e) {
            DB::rollback();

            return $e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     *  Belom Selesai
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        DB::beginTransaction();
        try {
            $anak = Anak::findOrFail($id);
            if ($anak->status_used) {
                $request->session()->flash('messages', 'Anak tidak dapat dihapus karena sudah terdapat data');
                $request->session()->flash('type', 'danger');

                return redirect()->back();
            }

            if (!empty($anak->foto)) {
                \File::delete(public_path('storage/anak/' . $anak->foto));
            }

            $anak->delete();

            DB::commit();

            $request->session()->flash('messages', 'Berhasil Menghapus Data Anak');
            $request->session()->flash('type', 'success');

            $sessionSelectedId = $request->session()->get('anak.id');

            if (auth()->user()->orang_tua->anak->count() > 0 && $id != $sessionSelectedId) {
                $redirect = redirect()->back();
            } else {
                $request->session()->forget('anak');
                $redirect = redirect()->route('orangtua.pilih_anak');
            }

            return $redirect;
        } catch (\Exception $e) {
            DB::rollback();

            return $e->getMessage();
        }
    }

    public function ConfirmAnak(Request $request, $id)
    {
        $anak = Anak::findOrFail($id);
        $request->session()->put('anak', $anak->only('id', 'nik', 'name', 'generateId', 'tgl_lahir', 'jenis_kelamin', 'alamat', 'foto', 'umur', 'tgl_lahir_formatted', 'jenis_kelamin_formatted', 'umur_bulan_formatted', 'umur_bulan', 'is_in_anggana_formatted', 'bapak', 'ibu', 'kecamatan', 'kelurahan', 'rt'));
        $role = auth()->user()->getRoleNames()->first();

        switch ($role) {
            case 'Petugas':
                $prefix = 'petugas.anak.index';
                break;

            default:
                $prefix = 'orangtua.home';
                break;
        }

        return redirect()->route($prefix);
    }
}

resources/views/shared/anak/vitamin/create.blade.php
@extends('layouts.app')

@section('content')
  <form method="POST" action={{ route('petugas.anak.vitamin.store') }}>
    @csrf
    @method('POST')
    <div class="container-fluid">
      <div class="row m-b-25">
        <div class="col-md-12">
          <div class="overview-wrap">
            <h2 class="title-1">
              Data Vitamin A
              <small class="text-muted">{{ Session::get('anak.name') }} / {{ Session::get('anak.umur_bulan_formatted') }} / {{ Session::get('anak.jenis_kelamin_formatted') }}</small>
            </h2>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <div class="card">
            <div class="card-header">
                <strong>Vitamin A</strong>
                <small> Tambah</small>
            </div>
            <div class="card-body card-block">
              <div class="form-group">
                <label for="tanggal" class="form-control-label">Tanggal</label>
                <input name="tanggal" type="text" id="tanggal" placeholder="Masukkan tanggal"
                  class="form-control @error('tanggal') is-invalid @enderror"
                  value={{ old('tanggal') }}>
                @error('tanggal')
                  <div class="invalid-feedback">
                    {{ $message }}
                  </div>
                @enderror
              </div>
              <div class="form-group">
                <label for="jenis" class="form-control-label">Jenis Vitamin A</label>
                <select name="jenis" id="jenis" class="form-control @error('jenis') is-invalid @enderror">
                  @php
                    $umur = Session::get('anak.umur_bulan');
                  @endphp
                  <option disabled selected value="0">Pilih jenis vitamin a</option>
                  <option value="biru"
                    @if(old('jenis') === 'biru') selected @endif
                    @if($umur < 6 || $umur > 11) disabled @endif
                  >
                    Kapsul Biru 6-11 Bulan
                    @if($umur < 6 || $umur > 11) (belum cukup umur / kelebihan umur) @endif
                  </option>
                  <option value="merah"
                    @if(old('jenis') === 'merah') selected @endif
                    @if($umur < 12 || $umur > 59) disabled @endif
                  >
                    Kapsul Merah 12-59 Bulan 
                    @if($umur < 12 || $umur > 59) (belum cukup umur / kelebihan umur) @endif
                  </option>
                </select>
                @error('jenis')
                  <div class="invalid-feedback">
                    {{ $message }}
                  </div>
                @enderror
              </div>
            </div>
            <div class="card-footer text-right">
              <a href={{ url('/petugas/anak/vitamin') }} type="reset" class="btn btn-danger">
                <i class="fa fa-ban"></i> Cancel
              </a>
              <button type="submit" class="btn btn-primary">
                <i class="fa fa-send"></i> Submit
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
@endsection

@push('script-addon')
  <script>
    $('#tanggal').datetimepicker({
      format: 'YYYY/MM/DD',
      defaultDate: moment()
    });
  </script>
@endpush

resources/views/shared/anak/vitamin/edit.blade.php
@extends('layouts.app')

@section('content')
  <form method="POST" action={{ route('petugas.anak.vitamin.update', $data->id) }}>
    @csrf
    @method('PUT')
    <div class="container-fluid">
      <div class="row m-b-25">
        <div class="col-md-12">
          <div class="overview-wrap">
            <h2 class="title-1">
              Data Vitamin A
              <small class="text-muted">{{ Session::get('anak.name') }} / {{ Session::get('anak.umur_bulan_formatted') }} / {{ Session::get('anak.jenis_kelamin_formatted') }}</small>
            </h2>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <div class="card">
            <div class="card-header">
                <strong>Vitamin A</strong>
                <small> Edit</small>
            </div>
            <div class="card-body card-block">
              <div class="form-group">
                <label for="tanggal" class="form-control-label">Tanggal</label>
                <input name="tanggal" type="text" id="tanggal" placeholder="Masukkan tanggal"
                  class="form-control @error('tanggal') is-invalid @enderror"
                  value={{ $data->tanggal }}>
                @error('tanggal')
                  <div class="invalid-feedback">
                    {{ $message }}
                  </div>
                @enderror
              </div>
              <div class="form-group">
                <label for="jenis" class="form-control-label">Jenis Vitamin A</label>
                <select name="jenis" id="jenis" class="form-control @error('jenis') is-invalid @enderror">
                  @php
                    $umur = Session::get('anak.umur_bulan');
                  @endphp
                  <option disabled selected value="0">Pilih jenis vitamin a</option>
                  <option value="biru"
                    @if($data->jenis === 'biru') selected @endif
                    @if($umur < 6 || $umur > 11) disabled @endif
                  >
                    Kapsul Biru 6-11 Bulan 
                    @if($umur < 6 || $umur > 11) (belum cukup umur / kelebihan umur) @endif
                  </option>
                  <option value="merah"
                    @if($data->jenis === 'merah') selected @endif
                    @if($umur < 12 || $umur > 59) disabled @endif
                  >
                    Kapsul Merah 12-59 Bulan 
                    @if($umur < 12 || $umur > 59) (belum cukup umur / kelebihan umur) @endif
                  </option>
                </select>
                @error('jenis')
                  <div class="invalid-feedback">
                    {{ $message }}
                  </div>
                @enderror
              </div>
            </div>
            <div class="card-footer text-right">
              <a href={{ url('/petugas/anak/vitamin') }} type="reset" class="btn btn-danger">
                <i class="fa fa-ban"></i> Cancel
              </a>
              <button type="submit" class="btn btn-primary">
                <i class="fa fa-send"></i> Submit
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
@endsection

@push('script-addon')
  <script>
    $('#tanggal').datetimepicker({
      format: 'YYYY/MM/DD',
      defaultDate: moment()
    });
  </script>
@endpush

resources/views/shared/anak/vitamin/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
  <div class="row m-b-25">
    <div class="col-md-12">
      <div class="overview-wrap">
        <h2 class="title-1">
          Data Vitamin A
          <small class="text-muted">{{ Session::get('anak.name') }} / {{ Session::get('anak.umur_bulan_formatted') }} / {{ Session::get('anak.jenis_kelamin_formatted') }}</small>
        </h2>
        @role('Petugas')
          <div>
            <a
              class="au-btn au-btn-icon au-btn--blue2 mr-2"
              href={{ url('/petugas/anak') }}
            >
              <i class="zmdi zmdi-arrow-left"></i>
              Kembali
            </a>
            <a
              class="au-btn au-btn-icon au-btn--blue"
              href={{ url('/petugas/anak/vitamin/create') }}
            >
              <i class="zmdi zmdi-plus"></i>
              Tambah vitamin a
            </a>
          </div>
        @endrole
      </div>
    </div>
  </div>
  @if ($msg = Session::get('messages'))
    <div class="row">
      <div class="col col-12">
        <div class="alert alert-block alert-{{ Session::get('type') }}">
          <p>{{ $msg }}</p>
        </div>      
      </div>
    </div>
  @endif
  <div class="row">
    <div class="col col-12">
      <div class="table-responsive">
        <table class="table table-borderless table-data3">
          <thead>
            <tr>
              <th>tanggal</th>
              <th>jenis vitamin a</th>
              <th>umur</th>
              <th>petugas</th>
              <th>posyandu</th>
              @role('Petugas')
                <th>option</th>
              @endrole
            </tr>
          </thead>
          <tbody>
            @forelse ($datas as $dt)
              <tr>
                <td>{{ $dt->tanggal_formatted }}</td>
                <td>{{ $dt->jenis_formatted }}</td>
                <td>{{ $dt->umur_bulan_formatted }}</td>
                <td>{{ $dt->petugas->user->name }}</td>
                <td>{{ $dt->posyandu->name }}</td>
                @role('Petugas')
                  @if ($dt->posyandu->id == Auth::user()->petugas->posyandu->id)
                    <td>
                      <a class="btn btn-sm btn-info d-inline-block" href={{ url('/petugas/anak/vitamin/'. $dt->id .'/edit') }}>Edit</a>
                      <form class="d-inline-block" method="post" action={{ url('/petugas/anak/vitamin/' . $dt->id) }} onSubmit="return confirm('Ingin menghapus?')">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                      </form>
                    </td>
                  @else
                    <td></td>
                  @endif
                @endrole
              </tr>
            @empty
              <tr>
                <td colspan="100%" class="text-center p-5"><h5>Tidak ada data.</h5></td>
              </tr>
            @endforelse
          </tbody>
        </table>
        <div class="d-flex justify-content-end m-t-25">
          {{ $datas->appends(request()->all())->links() }}
        </div>
      </div>
    </div>
  </div>
</div>
@endsection