routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::post('/register-orangtua', 'HomeController@RegisterOrangTua')->name('orangtua.register');

Auth::routes();

Route::get('/images/{folder}/{filename}', function ($folder, $filename) {
    $path = public_path('/storage/' . $folder . '/' . $filename);
    if (!File::exists($path)) {
        abort(404);
    }
    $file = File::get($path);
    $type = File::mimeType($path);
    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);
    return $response;
});

Route::group([
    'middleware' => ['auth', 'role:Admin'],
    'prefix' => 'admin',
    'as' => 'admin.'
], function () {
    Route::redirect('', '/admin/home');
    Route::get('/home',  'HomeController@AdminDashboard')->name('home');

    Route::resource('posyandu', 'PosyanduController');
    Route::resource('petugas', 'PetugasController');
    Route::resource('orangtua', 'OrangTuaController');

    Route::get('posyandu-rekap', 'PosyanduController@rekap_penimbangan_desa')->name('posyandu.rekap');
    Route::get('posyandu-rekap-print', 'PosyanduController@rekap_penimbangan_desa_print')->name('posyandu.rekap.print');
});

Route::group([
    'middleware' => ['auth', 'role:Petugas'],
    'prefix' => 'petugas',
    'as' => 'petugas.'
], function () {
    Route::redirect('', '/petugas/home');
    Route::get('/home',  'HomeController@PetugasDashboard')->name('home');

    Route::get('/cari-anak', 'AnakController@index')->name('anak.cari-anak');

    Route::get('/anak', function () {
        return view('petugas.anak.index');
    })->name('anak.index');

    Route::get('/anak/detail', function () {
        return view('petugas.anak.detail');
    })->name('anak.detail');

    Route::post('/confirm-anak/{id}', 'AnakController@ConfirmAnak')->name('confirm.anak');

    Route::resource('jadwal-kegiatan', 'JadwalKegiatanController');

    Route::get('posyandu-report', 'PenimbanganController@PosyanduReport')->name('posyandu.report');
    Route::get('posyandu-print', 'PenimbanganController@PosyanduPrint')->name('posyandu.print');

    Route::group([
        'prefix' => 'anak',
        'as' => 'anak.'
    ], function () {
        // Reports
        Route::get('imunisasi/report', 'ImunisasiController@report')->name('imunisasi.report');
        Route::get('vitamin/report', 'VitaminAController@report')->name('vitamin.report');
        Route::get('penimbangan/report', 'PenimbanganController@report')->name('penimbangan.report');

        // Prints
        Route::get('imunisasi/print', 'ImunisasiController@print')->name('imunisasi.print');
        Route::get('vitamin/print', 'VitaminAController@print')->name('vitamin.print');
        Route::get('penimbangan/print', 'PenimbanganController@print')->name('penimbangan.print');
        Route::group(['middleware' => 'NotInAnakSession'], function () {
            Route::resource('imunisasi', 'ImunisasiController')->except('show');
            Route::resource('vitamin', 'VitaminAController')->except('show');
            Route::resource('penimbangan', 'PenimbanganController')->except('show');
            Route::get('grafik', 'PenimbanganController@grafik')->name('penimbangan.grafik');
        });
    });
});

Route::group([
    'middleware' => ['auth', 'role:Orang_Tua'],
    'prefix' => 'orangtua',
    'as' => 'orangtua.'
], function () {
    Route::redirect('', '/orangtua/home');
    Route::get('/home',  'HomeController@OrangTuaDashboard')->name('home');

    Route::get('/pilih-anak', 'OrangTuaController@PilihAnak')->name('pilih_anak');
    Route::get('/tambah-anak', 'OrangTuaController@TambahAnak')->name('tambah_anak');
    Route::post('/confirm-anak/{id}', 'AnakController@ConfirmAnak')->name('confirm.anak');

    Route::resource('jadwal-kegiatan', 'JadwalKegiatanController')->only('index');

    Route::group([
        'prefix' => 'anak',
        'as' => 'anak.'
    ], function () {
        Route::redirect('', '/orangtua/anak/data');
        Route::resource('data', 'AnakController');
        Route::group(['middleware' => 'NotInAnakSession'], function () {
            Route::resource('imunisasi', 'ImunisasiController')->only('index');
            Route::resource('vitamin', 'VitaminAController')->only('index');
            Route::resource('penimbangan', 'PenimbanganController')->only('index');
            Route::get('grafik', 'PenimbanganController@grafik')->name('penimbangan.grafik');
        });
    });
});

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::get('jenis-imunisasi/{jenis}', function ($jenis) {
        return view('shared.jenis-imunisasi.' . $jenis);
    });
    Route::get('password', 'ProfileController@password')->name('profiles.get.password');
    Route::put('password', 'ProfileController@passwordPost')->name('profiles.post.password');
    Route::get('profile', 'ProfileController@profile')->name('profiles.get.profile');
    Route::put('profile', 'ProfileController@profilePost')->name('profiles.post.profile');
});

app/Models/Posyandu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Posyandu extends Model
{
    protected $table = 'posyandu';

    protected $fillable = [
        'code',
        'name',
        'jumlah_kader',
        'alamat',
        'rt',
        'kecamatan',
        'ketua',
        'desa',
    ];

    public $timestamps = true;

    protected $appends = ['status_used', 'jumlah_anak_l',  'jumlah_anak_p'];

    public function vitamin_a()
    {
        return $this->hasMany(VitaminA::class, 'posyandu_id');
    }

    public function imunisasi()
    {
        return $this->hasMany(Imunisasi::class, 'posyandu_id');
    }

    public function petugas()
    {
        return $this->hasMany(Petugas::class, 'posyandu_id');
    }

    public function penimbangan()
    {
        return $this->hasMany(Penimbangan::class, 'posyandu_id');
    }

    public function scopeFilter($query, $request)
    {
        if ($request->has('q')) {
            $query->where('code', 'like', '%' . $request->get('q') . '%')
                ->orWhere('name', 'like', '%' . $request->get('q') . '%')
                ->orWhere('ketua', 'like', '%' . $request->get('q') . '%');
        }

        return $query;
    }

    public function getStatusUsedattribute()
    {
        $status = false;

        $vitamin_a = $this->vitamin_a->count();
        $imunisasi = $this->imunisasi->count();
        $penimbangan = $this->penimbangan->count();
        $petugas = $this->petugas->count();

        if ($vitamin_a > 0) {
            $status = true;
        } elseif ($imunisasi > 0) {
            $status = true;
        } elseif ($penimbangan > 0) {
            $status = true;
        } elseif ($petugas > 0) {
            $status = true;
        }

        return $status;
    }

    public function getJumlahAnakAttribute()
    {
        $penimbangan = $this->penimbangan->groupBy('anak_id')->count();

        return $penimbangan;
    }

    public function getJumlahAnakPAttribute()
    {
        $penimbangan = $this->penimbangan()->whereHas('anak', function ($q) {
            $q->where('jenis_kelamin', 'PR');
        })->groupBy('anak_id')->get()->count();

        return $penimbangan;
    }

    public function getJumlahAnakLAttribute()
    {
        $penimbangan = $this->penimbangan()->whereHas('anak', function ($q) {
            $q->where('jenis_kelamin', 'LK');
        })->groupBy('anak_id')->get()->count();

        return $penimbangan;
    }
}

app/Http/Controllers/PosyanduController.php
<?php

namespace App\Http\Controllers;

use App\Models\Posyandu;
use Illuminate\Http\Request;
use App\Http\Requests\PosyanduRequest;
use App\Models\Petugas;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PosyanduController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = Posyandu::filter($request)->orderBy('code', 'ASC')->paginate(10);

        $views = [
            'datas' => $data
        ];

        return view('admin.posyandu.index')->with($views);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $id = $this->getLastCodePosyandu();
        $kelurahans = Petugas::kelurahan_choices();

        $views = [
            'kode_posyandu' => $id,
            'kelurahan_choices' => $kelurahans
        ];

        return view('admin.posyandu.create')->with($views);
    }

    /**
     * Store a newly created resource in storage.
     *
     * NOTE: Request => name, jumlah_kader, desa, ketua
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PosyanduRequest $request)
    {
        DB::beginTransaction();
        try {

            $request->merge(['code' => $this->getLastCodePosyandu()]);
            $wew = Posyandu::create($request->all());

            DB::commit();

            $request->session()->flash('messages', 'Berhasil Menambahkan Data Posyandu');
            $request->session()->flash('type', 'success');

            return redirect()->route('admin.posyandu.index');
        } catch (\Exception $e) {
            DB::rollback();

            return $e->getMessage();
        }
    }

    public function getLastCodePosyandu()
    {
        $last_data = Posyandu::orderBy('id', 'desc')->first();
        if ($last_data !== null) {
            $last_code = $this->splitCode($last_data->code);
        } else {
            $last_code = '000';
        }

        return 'P' . str_pad($last_code + 1, 3, '0', STR_PAD_LEFT);
    }

    private function splitCode($last_no_order)
    {
        return (int) substr($last_no_order, -3);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Posyandu::with('ketua')->findOrFail($id);

        $views = [
            'data'    => $data,
        ];

        return view('admin.posyandu.show')->with($views);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * Appends Status Used => False / True
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Posyandu::findOrFail($id);
        $kelurahans = Petugas::kelurahan_choices();

        $views = [
            'data'    => $data,
            'kelurahan_choices' => $kelurahans
        ];
        return view('admin.posyandu.edit')->with($views);
    }

    /**
     * Update the specified resource in storage.
     *
     * Request => name, jumlah_kader, desa, ketua
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PosyanduRequest $request, $id)
    {
        DB::beginTransaction();
        try {
            $data = Posyandu::findOrFail($id);
            $data->update($request->all());

            DB::commit();

            $request->session()->flash('messages', 'Berhasil Mengubah Data Posyandu');
            $request->session()->flash('type', 'success');

            return redirect()->route('admin.posyandu.index');
        } catch (\Exception $e) {
            DB::rollback();

            return $e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        DB::beginTransaction();
        try {
            $data = Posyandu::findOrFail($id);
            if ($data->status_used) {
                $request->session()->flash('messages', 'Posyandu tidak dapat dihapus karena sudah terdapat data');
                $request->session()->flash('type', 'danger');

                return redirect()->back();
            }

            $data->delete();

            DB::commit();

            $request->session()->flash('messages', 'Berhasil Menghapus Data Posyandu');
            $request->session()->flash('type', 'success');

            return redirect()->back();
        } catch (\Exception $e) {
            DB::rollback();

            return $e->getMessage();
        }
    }


    public function rekap_penimbangan_desa()
    {
        $kelurahans = Petugas::kelurahan_choices();
        $views = [
            'kelurahan_choices' => $kelurahans
        ];
        return view('admin.reports.posyandu-rekap')->with($views);
    }

    public function rekap_penimbangan_desa_print(Request $request)
    {
        // Anak Laki Laki = data->jumlah_anak_l
        // Anak Perempuan = data->jumlah_anak_p
        // Anak All = data->jumlah_anak

        $tanggal = $request->tanggal;
        $tanggal_new = explode("/", $tanggal);
        $bulan = $tanggal_new[1];
        $tahun = $tanggal_new[0];
        $tanggal_formatted = Carbon::createFromDate($tahun, $bulan, 1)->format('F Y');

        $posyandu = Posyandu::where('desa', $request->kelurahan)->whereHas('penimbangan', function ($q) use ($bulan, $tahun) {
            $q->whereMonth('tanggal', $bulan)->whereYear('tanggal', $tahun);
        })->get();

        $jumlah = $posyandu->sum('jumlah_anak');

        $views = [
            'datas' => $posyandu,
            'tanggal' => $tanggal_formatted,
            'kelurahan' => $request->kelurahan,
            'jumlah'    => $jumlah
        ];

        return view('admin.reports.print.posyandu-rekap')->with($views);
    }
}

resources/views/admin/posyandu/create.blade.php
@extends('layouts.app')

@section('content')
  <form method="POST" action={{ route('admin.posyandu.store') }}>
    @csrf
    @method('POST')
    <div class="card">
      <div class="card-header">
          <strong>Posyandu</strong>
          <small> Tambah</small>
      </div>
      <div class="card-body card-block">
        <div class="row form-group">
          <div class="col col-12 col-md-6">
            <label for="kode_posyandu" class="form-control-label">Kode Posyandu</label>
            <input name="code" value="{{ $kode_posyandu }}" disabled
              type="text" id="kode_posyandu" placeholder="Masukkan kode posyandu"
              class="form-control @error('code') is-invalid @enderror">
            @error('code')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
          <div class="col col-12 col-md-6">
            <label for="nama_posyandu" class="form-control-label">Nama Posyandu</label>
            <input name="name" value="{{ old('name') }}"
              type="text" id="nama_posyandu" placeholder="Masukkan nama posyandu"
              class="form-control @error('name') is-invalid @enderror">
            @error('name')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
        </div>
        <div class="row form-group">
          <div class="col col-12 col-md-6">
            <label for="ketua_posyandu" class="form-control-label">Ketua Posyandu</label>
            <input name="ketua" value="{{ old('ketua') }}"
              type="text" id="ketua_posyandu" placeholder="Masukkan ketua posyandu"
              class="form-control @error('ketua') is-invalid @enderror">
            @error('ketua')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
          <div class="col col-12 col-md-6">
            <label for="jumlah_kader" class="form-control-label">Jumlah Kader</label>
            <input name="jumlah_kader" value="{{ old('jumlah_kader') }}"
              type="number" id="jumlah_kader" placeholder="Masukkan jumlah kader"
              class="form-control @error('jumlah_kader') is-invalid @enderror">
            @error('jumlah_kader')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
        </div>
        <div class="row form-group">
          <div class="col col-12 col-md-6">
            <label for="kecamatan" class="form-control-label">Kecamatan</label>
            <input type="text" name="kecamatan" value="Anggana"
              type="text"
              id="kecamatan"
              class="form-control"
              readonly>
            @error('kecamatan')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
          <div class="col col-12 col-md-6">
            <label for="desa" class="form-control-label">Kelurahan/Desa</label>
            <select name="desa" id="desa"
              class="form-control @error('desa') is-invalid @enderror">
                <option disabled selected value="0">Pilih kelurahan/desa</option>
                @foreach ($kelurahan_choices as $kelurahan)
                  <option value="{{ $kelurahan }}" @if(old('desa') == $kelurahan) selected @endif>{{ $kelurahan }}</option>
                @endforeach
            </select>
            @error('desa')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
        </div>
        <div class="row form-group">
          <div class="col col-12 col-md-6">
            <label for="alamat" class="form-control-label">Alamat</label>
            <input name="alamat" type="text" value="{{ old('alamat') }}"
              id="alamat" placeholder="Masukkan alamat"
              class="form-control @error('alamat') is-invalid @enderror">
            @error('alamat')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
          <div class="col col-12 col-md-6">
            <label for="rt" class="form-control-label">RT</label>
            <input name="rt" type="text" value="{{ old('rt') }}"
              id="rt" placeholder="Masukkan rt"
              class="form-control @error('rt') is-invalid @enderror">
            @error('rt')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
        </div>
      </div>
      <div class="card-footer text-right">
        <a href={{ url('/admin/posyandu') }} type="reset" class="btn btn-danger">
          <i class="fa fa-ban"></i> Cancel
        </a>
        <button type="submit" class="btn btn-primary">
          <i class="fa fa-send"></i> Submit
        </button>
      </div>
    </div>
  </form>
@endsection

resources/views/admin/posyandu/edit.blade.php
@extends('layouts.app')

@section('content')
  <form method="POST" action={{ route('admin.posyandu.update', $data->id) }}>
    @csrf
    @method('PUT')
    <div class="card">
      <div class="card-header">
          <strong>Posyandu</strong>
          <small> Edit</small>
      </div>
      <div class="card-body card-block">
        <div class="row form-group">
          <div class="col col-12 col-md-6">
            <label for="kode_posyandu" class="form-control-label">Kode Posyandu</label>
            <input name="code" value="{{ $data->code }}"
              type="text" id="kode_posyandu" placeholder="Masukkan kode posyandu"
              class="form-control @error('code') is-invalid @enderror">
            @error('code')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
          <div class="col col-12 col-md-6">
            <label for="nama_posyandu" class="form-control-label">Nama Posyandu</label>
            <input name="name" value="{{ $data->name }}"
              type="text" id="nama_posyandu" placeholder="Masukkan nama posyandu"
              class="form-control @error('name') is-invalid @enderror">
            @error('name')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
        </div>
        <div class="row form-group">
          <div class="col col-12 col-md-6">
            <label for="ketua_posyandu" class="form-control-label">Ketua Posyandu</label>
            <input name="ketua" value="{{ $data->ketua }}"
              type="text" id="ketua_posyandu" placeholder="Masukkan ketua posyandu"
              class="form-control @error('ketua') is-invalid @enderror">
            @error('ketua')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
          <div class="col col-12 col-md-6">
            <label for="jumlah_kader" class="form-control-label">Jumlah Kader</label>
            <input name="jumlah_kader" value="{{ $data->jumlah_kader }}"
              type="number" id="jumlah_kader" placeholder="Masukkan jumlah kader"
              class="form-control @error('jumlah_kader') is-invalid @enderror">
            @error('jumlah_kader')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
        </div>
        <div class="row form-group">
          <div class="col col-12 col-md-6">
            <label for="kecamatan" class="form-control-label">Kecamatan</label>
            <input type="text" name="kecamatan" value="Anggana"
              type="text"
              id="kecamatan"
              class="form-control"
              readonly>
            @error('kecamatan')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
          <div class="col col-12 col-md-6">
            <label for="desa" class="form-control-label">Kelurahan/Desa</label>
            <select name="desa" id="desa"
              class="form-control @error('desa') is-invalid @enderror">
                <option disabled selected value="0">Pilih kelurahan/desa</option>
                @foreach ($kelurahan_choices as $kelurahan)
                  <option value="{{ $kelurahan }}" @if($data->desa == $kelurahan) selected @endif>{{ $kelurahan }}</option>
                @endforeach
            </select>
            @error('desa')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
        </div>
        <div class="row form-group">
          <div class="col col-12 col-md-6">
            <label for="alamat" class="form-control-label">Alamat</label>
            <input name="alamat" type="text" value="{{ $data->alamat }}"
              id="alamat" placeholder="Masukkan alamat"
              class="form-control @error('alamat') is-invalid @enderror">
            @error('alamat')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
          <div class="col col-12 col-md-6">
            <label for="rt" class="form-control-label">RT</label>
            <input name="rt" type="text" value="{{ $data->rt }}"
              id="rt" placeholder="Masukkan rt"
              class="form-control @error('rt') is-invalid @enderror">
            @error('rt')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>
        </div>
      </div>
      <div class="card-footer text-right">
        <a href={{ url('/admin/posyandu') }} type="reset" class="btn btn-danger">
          <i class="fa fa-ban"></i> Cancel
        </a>
        <button type="submit" class="btn btn-primary">
          <i class="fa fa-send"></i> Submit
        </button>
      </div>
    </div>
  </form>
@endsection

resources/views/admin/posyandu/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
  <div class="row m-b-25">
    <div class="col-md-12">
      <div class="overview-wrap">
        <h2 class="title-1">Posyandu</h2>
      </div>
    </div>
  </div>
  @if ($msg = Session::get('messages'))
    <div class="row">
      <div class="col col-12">
        <div class="alert alert-block alert-{{ Session::get('type') }}">
          <p>{{ $msg }}</p>
        </div>      
      </div>
    </div>
  @endif
  <div class="row">
    <div class="col col-12 col-md-6 m-b-25">
      <form class="form-header" method="GET" action="{{ url('/admin/posyandu') }}">
        <input class="au-input au-input--sm" type="text" name="q" placeholder="Search..." value="{{ request()->get('q') }}" />
        <button class="au-btn--submit" type="submit">
            <i class="zmdi zmdi-search"></i>
        </button>
      </form>
    </div>
    <div class="col col-12 col-md-6 m-b-25 d-flex justify-content-center justify-content-md-end">
      <a
          class="au-btn au-btn-icon au-btn--blue"
          href={{ url('/admin/posyandu/create') }}
        >
          <i class="zmdi zmdi-plus"></i>
          Tambah posyandu
      </a>
    </div>
  </div>
  <div class="row">
    <div class="col col-12">
      <div class="table-responsive">
        <table class="table table-borderless table-data3">
          <thead>
            <tr>
              <th>kode</th>
              <th>nama</th>
              <th>desa</th>
              <th>jumlah kader</th>
              <th>ketua</th>
              <th>option</th>
            </tr>
          </thead>
          <tbody>
            @forelse ($datas as $dt)
              <tr>
                <td>{{ $dt->code }}</td>
                <td>{{ $dt->name }}</td>
                <td>{{ $dt->desa }}</td>
                <td>{{ $dt->jumlah_kader }}</td>
                <td>{{ $dt->ketua }}</td>
                <td>
                  <a class="btn btn-sm btn-info d-inline-block" href={{ url('/admin/posyandu/'. $dt->id .'/edit') }}>Edit</a>
                  <form class="d-inline-block" method="post" action={{ url('/admin/posyandu/' . $dt->id) }} onSubmit="return confirm('Ingin menghapus?')">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                  </form>
                </td>
              </tr>
            @empty
              <tr>
                <td colspan="100%" class="text-center p-5"><h5>Tidak ada data.</h5></td>
              </tr>
            @endforelse
          </tbody>
        </table>
      </div>
      <div class="d-flex justify-content-end m-t-25">
        {{ $datas->appends(request()->all())->links() }}
      </div>
    </div>
  </div>
</div>
@endsection